### ISSUE TITLE
Can you know the characteristics of the preprocessed data and the meaning of the numerical values?

### ISSUE THREAD

**Issue by Moon-creat** [bit-ml/AnoShift#2]
![image](https://github.com/bit-ml/AnoShift/assets/129244270/2f9ba777-6fd2-44f0-9421-882587a8f22e)
I'm not quite sure what this data means

**Comment by marviss** [comment]
Hello @wunengwu !

You can find a description of columns 0-13 (conventional features) in the [original metadata](https://www.takakura.com/Kyoto_data/BenchmarkData-Description-New.pdf), with column indices shifted by one.

We detail the preprocessing method in section 3.2.1 in our [paper](https://arxiv.org/pdf/2206.15476.pdf). In short, columns 0, 2 and 3, which have numerical values in the original data, are binned and replaced with bin labels (such as "c00", "c30" etc.). Columns 1 and 13 are categorical, while the values of the rest of the columns are percentages.
