### ISSUE TITLE
Link to the pre-processed dataset cannot be opened

### ISSUE THREAD

**Issue by Jizhou-Chen** [bit-ml/AnoShift#4]
Thank you for providing this awesome dataset. I found that this link cannot be opened anymore. Could you take a look? Thanks!

> Preprocessed Kyoto-2006+ data available at: https://share.bitdefender.com/s/9D4bBE7H8XTdYDB

**Comment by marviss** [comment]
Hello! We are in process of changing the data storage system and unfortunately the URL we provided is unavailable for now. We will get back to you as soon as possible with the new data access link.

Best regards!

**Comment by marviss** [comment]
Hello!

The dataset is now available at: https://storage.googleapis.com/bitdefender_ml_artifacts/anoshift/Kyoto-2016_AnoShift.tar

:)
